### ISSUE TITLE
Version of Coq used in the tutorial

### ISSUE THREAD

**Issue by MSoegtropIMC** [AllanBlanchard/tutoriel_wp#19]
First let me say thank you for this nice tutorial!

I have one question: is there a specific reason for using Coq 8.9.0 in a document from March 2020? Are there issues with the tools when more recent versions of Coq are used or is it just a bit hard to setup so that you keep your setup for a few years?

You might want to leave a few words in the tutorial on the rationale behind this and some advice.

**Comment by AllanBlanchard** [comment]
> First let me say thank you for this nice tutorial!

You're welcome :)

> I have one question: is there a specific reason for using Coq 8.9.0 in a document from March 2020? Are there issues with the tools when more recent versions of Coq are used or is it just a bit hard to setup so that you keep your setup for a few years?

Normally, more recent versions should be fine. In fact, since the current native Coq support is deprecated (even though we are still working on the Why3+Coq support), the validation of WP is still done using 8.9.0, so I do not install a more recent one. We try more recent versions of Coq at each new version but as far as I know there are no particular problems due to the versions of Coq for quite some time now (but we could have missed something).

However, there was a problem with the support of Coq (no matter the version) in Calcium for the function `region` which is sometimes used in proof obligations. We found it in Frama-C 21 fixed it in Frama-C 21.1. As Coq is mostly (if not always) used for lemmas, and not for assertions, the `region` function was almost never used.

> You might want to leave a few words in the tutorial on the rationale behind this and some advice.

You are right. For the upcoming new version of the tutorial I will run my proof scripts with the most recent version of Coq to check whether everything goes well.

Thank you for the advice!

**Comment by AllanBlanchard** [comment]
Ok, I just checked with 8.11.2 and it succeeds, I will ad a few words about that.

**Comment by AllanBlanchard** [comment]
I have added a few words in the next version of the tutoriel, which will be available soon.

**Comment by MSoegtropIMC** [comment]
Thanks for the clarification! That it works with 8.11.2 gives confidence that this is actively maintained.
